version: '3.8'

services:
  webapp:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8080:80
    environment:
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: db

  db:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: somewordpress
    ports:
      - 5000:80

volumes:
  db_data: {}
